apiVersion: apps/v1  
kind: Deployment
metadata:
  name: spring-boot-app 
  labels:
    app: spring-boot-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-boot-app
  template:
    metadata:
      labels:
        app: spring-boot-app
    spec:
      containers:
      - name: spring-boot-app
        #image: jewetest.jfrog.io/docker/ultimate-cicd-pipeline:v1
        image: 592931362264.dkr.ecr.ap-southeast-1.amazonaws.com/ula-dev-eks-workshop
        ports:
        - containerPort: 8080
      #imagePullSecrets:
      #- name: regcred
